name: nona
channels:
  - defaults
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - idna=3.4
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.7.16
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.6.3
  - sqlite=3.41.2
  - tk=8.6.12
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - seaborn=0.12.2
  - pandas=1.3.5
  - matplotlib=3.5.3
  - scipy=1.7